groups:
  runewake2:
  - admin
  - all-access
  Greenhottub:
  - all-access
  xxxOOZxxx:
  - all-access
player_limit: -1
ip_forward: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  all-access:
  - bungeecord.server.survival
  - bungeecord.server.creative
  - bungeecord.server.arena
  admin:
  - bungeecord.command.alert
  - bungeecord.command.find
  - bungeecord.command.send
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
log_commands: false
online_mode: true
servers:
  lobby:
    motd: '&1The World of Zero Minecraft Hub'
    address: 192.168.1.58:25560
    restricted: false
  survival:
    motd: '&1The Survival Server'
    address: 192.168.1.58:25561
    restricted: true
  creative:
    motd: '&1The Creative Server'
    address: 192.168.1.58:25562
    restricted: true
  arena:
    motd: '&1The Arena Minigame'
    address: 192.168.1.58:25563
    restricted: true
listeners:
- query_port: 25577
  motd: '&1A World of Zero Minecraft Server'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
  proxy_protocol: false
disabled_commands:
- disabledcommandhere
network_compression_threshold: 256
connection_throttle: 4000
connection_throttle_limit: 3
stats: f2876aa6-74d2-468c-90ee-1377111f1c9f
forge_support: false
inject_commands: false