version: '3.5'
services:
  mc_hub:
    container_name: mc_hub
    image: itzg/minecraft-server
    restart: 'unless-stopped'
    ports:
      - 25560:25565
    environment:
      EULA: 'TRUE'
      DIFFICULTY: 'peaceful'
      TYPE: 'SPIGOT'
      # ADMINS
      OPS: runewake2
      ONLINE_MODE: 'FALSE'

      # PLAYER SETTINGS
      ANNOUNCE_PLAYER_ACHIEVEMENTS: 'FALSE'
      MAX_PLAYERS: 50

      # SERVER CONFIG
      MAX_WORLD_SIZE: 1000
      MEMORY: '2G'
      BUILD_FROM_SOURCE: 'TRUE'
    volumes:
      - /home/clouduser/minecraft-hub/data:/data
    tty: true
    stdin_open: true
  mc_survival:
    container_name: mc_survival
    image: itzg/minecraft-server
    restart: 'unless-stopped'
    ports:
      - 25561:25565
    environment:
      EULA: 'TRUE'
      DIFFICULTY: 'hard'
      MOTD: 'Welcome to the World of Zero Minecraft Server'
      ICON: 'https://yt3.ggpht.com/OTQmOnaALjPc9MK8zRNmGRqWDR8tkcmKVF3nhHqYpTGm6dx_yKQdP29GmS9ygR4JuVRMmDsjtuo'
      TYPE: 'SPIGOT'
      SEED: '-2043652089'
      # ADMINS
      OPS: runewake2
      ONLINE_MODE: 'FALSE'

      # PLAYER SETTINGS
      ANNOUNCE_PLAYER_ACHIEVEMENTS: 'FALSE'
      MAX_PLAYERS: 50

      # SERVER CONFIG
      MEMORY: '2G'
      BUILD_FROM_SOURCE: 'TRUE'
    volumes:
      - /home/clouduser/minecraft/data:/data
    tty: true
    stdin_open: true
  mc_creative:
    container_name: mc_creative
    image: itzg/minecraft-server
    restart: 'unless-stopped'
    ports:
      - 25562:25565
    environment:
      EULA: 'TRUE'
      DIFFICULTY: 'peaceful'
      TYPE: 'SPIGOT'
      # ADMINS
      OPS: runewake2
      ONLINE_MODE: 'FALSE'
      ENABLE_COMMAND_BLOCK: 'TRUE'

      # PLAYER SETTINGS
      ANNOUNCE_PLAYER_ACHIEVEMENTS: 'FALSE'
      MAX_PLAYERS: 50

      # SERVER CONFIG
      MAX_WORLD_SIZE: 1000
      MEMORY: '2G'
      BUILD_FROM_SOURCE: 'TRUE'
    volumes:
      - /home/clouduser/minecraft-creative/data:/data
    tty: true
    stdin_open: true
  mc_arena:
    container_name: mc_arena
    image: itzg/minecraft-server
    restart: 'unless-stopped'
    ports:
      - 25563:25565
    environment:
      EULA: 'TRUE'
      DIFFICULTY: 'peaceful'
      TYPE: 'SPIGOT'
      # ADMINS
      OPS: runewake2
      ONLINE_MODE: 'FALSE'
      ENABLE_COMMAND_BLOCK: 'TRUE'

      # PLAYER SETTINGS
      ANNOUNCE_PLAYER_ACHIEVEMENTS: 'FALSE'
      MAX_PLAYERS: 50

      # SERVER CONFIG
      MAX_WORLD_SIZE: 1000
      MEMORY: '2G'
      BUILD_FROM_SOURCE: 'TRUE'
    volumes:
      - /home/clouduser/minecraft-arena/data:/data
    tty: true
    stdin_open: true
  bungeecord:
    container_name: bungeecord
    image: itzg/bungeecord
    depends_on:
      - mc_hub
      - mc_survival
      - mc_creative
      - mc_arena
    ports:
      - 25565:25577
    volumes:
      - ./config.yml:/server/config.yml
    links:
      - mc_hub
      - mc_survival
      - mc_creative
      - mc_arena