connection_throttle_limit: 3
timeout: 30000
online_mode: true
log_commands: false
network_compression_threshold: 256
listeners:
- query_port: 25577
  motd: '&1A World of Zero Minecraft Server'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
  proxy_protocol: false
connection_throttle: 4000
groups:
  runewake2:
  - admin
  - all-access
log_pings: true
ip_forward: false
prevent_proxy_connections: false
forge_support: false
inject_commands: false
disabled_commands:
- disabledcommandhere
stats: f2876aa6-74d2-468c-90ee-1377111f1c9f
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.find
  - bungeecord.command.send
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  lobby:
    motd: '&1The World of Zero Minecraft Hub'
    address: mchub
    restricted: false
player_limit: -1
