apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mc_mysql:3306
    database: mc_database
    user: mc_user
    password: mc_password
    jsonData:
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+