# A list of scrape configurations.
global:
  # How frequently to scrape targets by default.
  scrape_interval: 1s

scrape_configs:
  - job_name: 'minecraft'
    static_configs:
      - targets: ['mc_hub:9225']
        labels:
          server_name: 'hub'
      - targets: ['mc_survival:9225']
        labels:
          server_name: 'survival'